services:
  - type: web
    name: cisf-qm-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: <your_postgres_connection_url>
      - key: WKHTMLTOPDF_PATH
        value: /usr/bin/wkhtmltopdf
